# Use a base image with Python pre-installed
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the application code to the container
COPY . /app

# Install any required dependencies
RUN pip install -r requirements.txt

# Update pip
RUN pip install --upgrade pip

# Set the command to run your application
CMD ["python", "flaskApplication.py"]
