name: Build and Push Docker Image

on:
  push:
    branches:
      - flaskmain

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: /Users/eubarkana/Documents/FlaskPython/DockerFile/flaskDockerfile

    - name: Build the Docker image
      run: docker build -t flask-python-test:${{ github.sha }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: docker push flask-python-test:${{ github.sha }}

